[package]
name = "renderer"
version = "0.1.0"
authors = ["Cloud Han <cloudhan@outlook.com>"]

[dependencies]
xml-rs = "0.8.0"
nalgebra = "0.16.0"
rand = "0.5.5"
num-traits = "0.2"
openexr = { git = "https://github.com/cloudhan/openexr-rs" }